# extract_rag_data.py
"""
Builds the complete RAG dataset and in-browser knowledge chunks from nuptial_flight_factors_updated.pdf.
Outputs:
1. nuptial_rag_dataset.json (Machine-readable full dataset with chunk embeddings/text)
2. rag_data.js (Browser-ready dataset and chunk retrieval index)
"""

import json
import os

TIER_DEFINITIONS = {
    "TIER_1": {
        "title": "Tier 1 — Quantified Experimental / Field Data",
        "description": "Peer-reviewed studies that measured actual temperature, humidity, wind, or timing thresholds against observed flights.",
        "badge": "Tier 1 · Quantified Field Data",
        "confidence_level": "Highest",
        "reliability_score": 5
    },
    "TIER_2": {
        "title": "Tier 2 — Documented Qualitative Pattern (incl. Indian species)",
        "description": "Peer-reviewed or authoritative sources describing seasonal timing and general trigger conditions without precise numeric thresholds.",
        "badge": "Tier 2 · Documented Pattern",
        "confidence_level": "High",
        "reliability_score": 4
    },
    "TIER_3": {
        "title": "Tier 3 — Reproductive-Strategy Exceptions (No Classic Flight)",
        "description": "Species documented to not perform classic aerial nuptial flights at all (supercolonial/tramp species) — critical negative data points to prevent false flight predictions.",
        "badge": "Tier 3 · Non-Flying / Intranidal",
        "confidence_level": "Verified Exception",
        "reliability_score": 5
    },
    "TIER_4": {
        "title": "Tier 4 — Citizen-Science / Antkeeping Community Data",
        "description": "Aggregated hobbyist observation calendars (AntScout, AntFlights.com, AntonTop). Directionally useful but not peer-reviewed.",
        "badge": "Tier 4 · Citizen Science",
        "confidence_level": "Moderate",
        "reliability_score": 3
    },
    "TIER_5": {
        "title": "Tier 5 — India-Specific Context (Monsoon Biology, Not Direct Flight-Trigger Data)",
        "description": "Well-studied Indian species where literature documents monsoon-adaptive biology in detail, but does NOT report specific nuptial-flight weather triggers.",
        "badge": "Tier 5 · Monsoon Biology",
        "confidence_level": "Contextual (No Flight Data)",
        "reliability_score": 3
    },
    "TIER_6": {
        "title": "Tier 6 — Additional India-Occurring Species (Predicted, by City)",
        "description": "Species confirmed present in Indian cities via faunal checklists and urban ant surveys, with predictions inferred from closest documented relatives in Tiers 1–5.",
        "badge": "Tier 6 · Inferred / Predicted",
        "confidence_level": "Inferred",
        "reliability_score": 2
    }
}

SPECIES_DATA = [
    # --- TIER 1 ---
    {
        "id": "SOL-INV",
        "name": "Red Imported Fire Ant",
        "sci": "Solenopsis invicta",
        "tier": "TIER_1",
        "region": "Native: South America. Invasive: southern USA, China, Australia, global.",
        "zone": "NA_GLOBAL",
        "tempRange": [25, 35],
        "tempText": "25–35°C ambient (70–90°F range also cited); larval development optimal 24–36°C.",
        "humidityRange": [60, 80],
        "humidityText": "60–80% relative humidity.",
        "rainfallPattern": "Within ~24 hours after rainfall while humidity is still elevated; in Guangdong field data, flights were most frequent after rain.",
        "condition": "after_rain",
        "windMax": 8,
        "windText": "Calm, at or below ~8 km/h.",
        "timingText": "Late spring–early summer onset; daily window 9:00–15:00 (no night flights recorded); duration ~30 min.",
        "months": [4, 5, 6, 7, 8, 9],
        "timeOfDay": ["morning", "afternoon"],
        "notes": "One of the best-quantified species globally due to its status as a major agricultural/urban pest; extensively used as a baseline.",
        "source": "LSU AgCenter pest profile; Animal Diversity Web; Xu, Huang, Lu, Zeng & Liang (2009) Sociobiology 54:831–840 (Guangdong field observations)."
    },
    {
        "id": "MES-BAR",
        "name": "Iberian Harvester Ant",
        "sci": "Messor barbarus",
        "tier": "TIER_1",
        "region": "Southern Spain, Portugal, N. Africa (Mediterranean semi-arid).",
        "zone": "EU",
        "tempRange": [15, 35],
        "tempText": "Foraging active 15–35°C; flights favoured by warm, stable anticyclonic weather following a rain front.",
        "humidityRange": [50, 95],
        "humidityText": "Elevated post-rain humidity aids excavation of the moistened soil.",
        "rainfallPattern": "Flights strongly clustered around specific autumn rain fronts (peak activity 2–3 days after precipitation).",
        "condition": "after_rain",
        "windMax": 10,
        "windText": "Low wind required for synchronized regional emergence.",
        "timingText": "Main season September–October (some populations also fly spring, March–June); daily window common in mornings.",
        "months": [3, 4, 5, 6, 9, 10],
        "timeOfDay": ["morning"],
        "notes": "123 nuptial-flight observations (2003–2009) across the Iberian Peninsula formed 8 distinct weather-front-linked clusters.",
        "source": "Gómez & Abril (2012) Myrmecological News 16:25–29."
    },
    {
        "id": "LAS-NIG",
        "name": "Black Garden Ant",
        "sci": "Lasius niger",
        "tier": "TIER_1",
        "region": "Netherlands / UK / NW Europe / introduced North America.",
        "zone": "EU_NA",
        "tempRange": [20, 30],
        "tempText": "Warm afternoons, generally >24°C reported in UK synthesis.",
        "humidityRange": [55, 95],
        "humidityText": "Significant differences in relative humidity at flight onset recorded vs. non-flight days.",
        "rainfallPattern": "Flights typically follow a rainstorm while air is still humid; not strictly rain-dependent every year.",
        "condition": "humid_still_evening",
        "windMax": 15,
        "windText": "<1.7 m/s before 20 August in the original study; UK sources cite a general ceiling around 6–7 m/s (~22 km/h).",
        "timingText": "L. niger: July–August, UK peak afternoon ~17:00, 11-hr window 10:00–20:00 in aggregated citizen records.",
        "months": [7, 8],
        "timeOfDay": ["afternoon", "dusk", "evening"],
        "notes": "Multi-year meteorological-station-matched dataset; a genuinely rare case of controlled comparison across sympatric species ('Flying Ant Day').",
        "source": "Boomsma & Leusink (1981) Oecologia 48:206–213; NHM 'Flying Ant Day' explainer."
    },
    {
        "id": "LAS-FLA",
        "name": "Yellow Meadow Ant",
        "sci": "Lasius flavus",
        "tier": "TIER_1",
        "region": "Netherlands / UK / Central & NW Europe.",
        "zone": "EU",
        "tempRange": [18, 28],
        "tempText": "Warm afternoons, generally >24°C reported in UK synthesis.",
        "humidityRange": [55, 95],
        "humidityText": "Significant differences in relative humidity at flight onset vs. non-flight days.",
        "rainfallPattern": "Flights typically follow a rainstorm while air is humid.",
        "condition": "warm_calm_afternoon",
        "windMax": 14,
        "windText": "<1.7 m/s before 20 August; ceiling around 6–7 m/s.",
        "timingText": "Main flights late summer (August–September), afternoon windows.",
        "months": [8, 9],
        "timeOfDay": ["afternoon"],
        "notes": "Part of the temperate European trio measured against weather stations.",
        "source": "Boomsma & Leusink (1981) Oecologia 48:206–213."
    },
    {
        "id": "MYR-RUB",
        "name": "European Fire Ant",
        "sci": "Myrmica rubra",
        "tier": "TIER_1",
        "region": "Netherlands / UK / Europe / introduced North America.",
        "zone": "EU_NA",
        "tempRange": [19, 28],
        "tempText": "Warm afternoons, >24°C in summer.",
        "humidityRange": [55, 95],
        "humidityText": "Significant differences in relative humidity at flight onset vs non-flight days.",
        "rainfallPattern": "Typically follows rain while air is still humid.",
        "condition": "warm_calm_afternoon",
        "windMax": 14,
        "windText": "<1.7 m/s early season, ceiling around 6–7 m/s.",
        "timingText": "Mid-to-late summer (July–August), afternoon emergence.",
        "months": [7, 8],
        "timeOfDay": ["afternoon"],
        "notes": "Sympatric European trio member verified in Oecologia field study.",
        "source": "Boomsma & Leusink (1981) Oecologia 48:206–213."
    },
    {
        "id": "MYR-SCA",
        "name": "European Moss Ant",
        "sci": "Myrmica scabrinodis",
        "tier": "TIER_1",
        "region": "NW Europe (Netherlands, UK).",
        "zone": "EU",
        "tempRange": [16, 28],
        "tempText": "No statistically defined temperature preference found.",
        "humidityRange": [40, 95],
        "humidityText": "No statistically defined humidity preference found.",
        "rainfallPattern": "Not distinctly rain-linked in the dataset.",
        "condition": "warm_calm_afternoon",
        "windMax": 15,
        "windText": "Same wind ceiling as co-occurring species after 20 August.",
        "timingText": "Flies within the same general summer window as the other three species studied.",
        "months": [7, 8, 9],
        "timeOfDay": ["afternoon", "evening"],
        "notes": "Included specifically because it is a documented negative result: unlike its co-occurring relatives, triggers vary.",
        "source": "Boomsma & Leusink (1981) Oecologia 48:206–213."
    },
    {
        "id": "MAN-RUB",
        "name": "Mountain Red Ant",
        "sci": "Manica rubida",
        "tier": "TIER_1",
        "region": "Southern Poland, Central European highlands.",
        "zone": "EU",
        "tempRange": [15, 26],
        "tempText": "Not separately quantified in source; occurs in a cooler, moister climate than Mediterranean species.",
        "humidityRange": [50, 95],
        "humidityText": "Not separately quantified; ambient humidity in the region is comparatively high year-round.",
        "rainfallPattern": "No rainfall recorded in the 24 hours preceding flights studied; rain instead followed the flight (same or next day).",
        "condition": "calm_mild_morning",
        "windMax": 12,
        "windText": "Not quantified in source.",
        "timingText": "Summer, exact dates not specified in the abstract-level source.",
        "months": [6, 7, 8],
        "timeOfDay": ["morning", "afternoon"],
        "notes": "Directly contrasts with Messor barbarus: illustrates that 'fly after rain' is a dry/seasonal-climate pattern, not a universal rule.",
        "source": "Depa (2006) Myrmecologische Nachrichten 9:27–32, as cited in Gómez & Abril (2012)."
    },
    {
        "id": "OEC-LON",
        "name": "African Weaver Ant",
        "sci": "Oecophylla longinoda",
        "tier": "TIER_1",
        "region": "Tanzania (cashew-growing regions), Sub-Saharan Africa.",
        "zone": "AFRICA",
        "tempRange": [22, 34],
        "tempText": "Not numerically isolated in source; occurs during the tropical rainy season.",
        "humidityRange": [70, 98],
        "humidityText": "Flight days had significantly higher relative humidity than non-flight days.",
        "rainfallPattern": "Flights occur during the rainy season.",
        "condition": "monsoon_humidity",
        "windMax": 12,
        "windText": "Not quantified.",
        "timingText": "All 56 recorded flights occurred in the evening, just before sunset.",
        "months": [3, 4, 5, 10, 11, 12],
        "timeOfDay": ["dusk", "evening"],
        "notes": "Flight days also had significantly less sunshine than non-flight days — i.e. overcast, humid evenings are the strongest trigger.",
        "source": "Peng, Renneberg & Offenberg (2015) Insectes Sociaux 62:469–476."
    },

    # --- TIER 2 ---
    {
        "id": "OEC-SMA",
        "name": "Asian Weaver Ant",
        "sci": "Oecophylla smaragdina",
        "tier": "TIER_2",
        "region": "India (recorded in Gujarat, Assam, Meghalaya, Tamil Nadu, Odisha), through SE Asia to northern Australia.",
        "zone": "SA",
        "tempRange": [25, 36],
        "tempText": "Not numerically quantified for India; Australian population studies show sexual-form production is temperature-gated.",
        "humidityRange": [60, 95],
        "humidityText": "Not numerically quantified; elevated during monsoon.",
        "rainfallPattern": "Indian field studies explicitly describe nuptial flights occurring during the monsoon season; a Laos/Australia-wide pattern.",
        "condition": "after_rain",
        "windMax": 15,
        "windText": "Not quantified.",
        "timingText": "Morning after sunrise through around noon; reproduction levels highest in wet season and early dry season.",
        "months": [5, 6, 7, 8, 9],
        "timeOfDay": ["morning", "afternoon"],
        "notes": "The most India-relevant weaver-ant data available; multiple Indian nesting-ecology papers explicitly flag weather links.",
        "source": "Multiple Indian field papers (Gujarat, Assam, Meghalaya, Tamil Nadu, Odisha); Lokkers (1990) PhD thesis, James Cook University."
    },
    {
        "id": "CAM-SER",
        "name": "Silky Camponotus Ant",
        "sci": "Camponotus sericeus",
        "tier": "TIER_2",
        "region": "India and broader Southeast Asian/Afrotropical ranges.",
        "zone": "SA",
        "tempRange": [24, 34],
        "tempText": "Not explicitly quantified for flight, though reproductive cycles are climate-adapted.",
        "humidityRange": [50, 95],
        "humidityText": "Not numerically quantified.",
        "rainfallPattern": "Flights are reported to follow the monsoon season cycle.",
        "condition": "after_rain",
        "windMax": 15,
        "windText": "Not quantified.",
        "timingText": "Reported to occur in September–October in India, with alates said to develop from October to July and be present year-round.",
        "months": [9, 10],
        "timeOfDay": ["afternoon", "dusk", "evening"],
        "notes": "Editor's flag: demonstrates a distinct temporal-gating claim — flights allegedly wait for seasonal cues rather than occurring as soon as reproductives mature. Treat this entry as lower confidence than other Tier 2 rows pending source verification.",
        "source": "Cited in submitted text as 'Kipyatkov, V.E. (2018)'; actual 2018 chapter authored by E.B. Lopatina (general Palearctic review). Treat citation with caveat."
    },
    {
        "id": "POG-RUG",
        "name": "Desert Harvester Ant",
        "sci": "Pogonomyrmex rugosus",
        "tier": "TIER_2",
        "region": "Southwestern USA deserts.",
        "zone": "NA",
        "tempRange": [26, 38],
        "tempText": "Not quantified in the cited comparative source.",
        "humidityRange": [30, 85],
        "humidityText": "Not quantified.",
        "rainfallPattern": "Phenology explicitly constrained by moisture availability, cited as a parallel case to Messor barbarus — flights follow rain.",
        "condition": "monsoon_humidity",
        "windMax": 14,
        "windText": "Not quantified.",
        "timingText": "Restricted, unpredictable windows tied to rainfall events rather than a fixed calendar month.",
        "months": [6, 7, 8, 9],
        "timeOfDay": ["morning", "afternoon"],
        "notes": "Illustrative of the general desert-ant pattern: in arid systems, rainfall (not temperature or season per se) is the binding trigger.",
        "source": "Helms & Helms Cahan (2010), as cited in Gómez & Abril (2012)."
    },
    {
        "id": "ATT-SEX",
        "name": "Leaf-cutter Ant",
        "sci": "Atta sexdens rubropilosa",
        "tier": "TIER_2",
        "region": "Brazil / South America (tropical).",
        "zone": "SA_AMERICA",
        "tempRange": [22, 32],
        "tempText": "Warm tropical temperatures typical of onset-of-rains period.",
        "humidityRange": [65, 95],
        "humidityText": "Rises sharply with monsoon/rainy-season onset.",
        "rainfallPattern": "Nuptial flights documented to coincide with the onset of the rainy season (October–November).",
        "condition": "after_rain",
        "windMax": 12,
        "windText": "Not quantified.",
        "timingText": "Tied to rainy-season onset rather than a fixed date.",
        "months": [10, 11],
        "timeOfDay": ["afternoon", "evening"],
        "notes": "Included as the reference case for the broader 'leaf-cutter ants fly at monsoon onset' pattern often generalized.",
        "source": "General leaf-cutter ant nuptial-flight literature; Hölldobler & Wilson (1990)."
    },

    # --- TIER 3 (Reproductive-Strategy Exceptions / Tramp Species) ---
    {
        "id": "LIN-HUM",
        "name": "Argentine Ant",
        "sci": "Linepithema humile",
        "tier": "TIER_3",
        "region": "Native: South America. Invasive: worldwide, forms the largest known ant supercolonies.",
        "zone": "GLOBAL",
        "isNonFlying": True,
        "tempRange": [0, 50],
        "tempText": "N/A — Does not fly.",
        "humidityRange": [0, 100],
        "humidityText": "N/A",
        "rainfallPattern": "N/A — No weather-triggered nuptial flight.",
        "condition": "none",
        "windMax": 99,
        "windText": "N/A",
        "timingText": "N/A (Dispersal via budding).",
        "months": [],
        "timeOfDay": [],
        "notes": "Supercolonial/unicolonial species: mating is largely intranidal (occurs inside the nest), not via aerial dispersal. Do NOT force flight predictions.",
        "source": "Eyer, Blumenfeld & Vargo (2019) Ecology and Evolution; Cini et al. (2022) Myrmecological News 32:1–22."
    },
    {
        "id": "MON-PHA",
        "name": "Pharaoh Ant",
        "sci": "Monomorium pharaonis",
        "tier": "TIER_3",
        "region": "Believed native to Africa/Asia; now a cosmopolitan indoor pest worldwide, including India.",
        "zone": "GLOBAL",
        "isNonFlying": True,
        "tempRange": [0, 50],
        "tempText": "N/A",
        "humidityRange": [0, 100],
        "humidityText": "N/A",
        "rainfallPattern": "N/A",
        "condition": "none",
        "windMax": 99,
        "windText": "N/A",
        "timingText": "N/A",
        "months": [],
        "timeOfDay": [],
        "notes": "Nuptial flights outdoors are rare to essentially absent. New queens mate within the nest; winged alates do not rely on weather triggers.",
        "source": "Hymenoptera reproductive-strategy literature; general pest-identification references."
    },
    {
        "id": "ANO-GRA",
        "name": "Yellow Crazy Ant",
        "sci": "Anoplolepis gracilipes",
        "tier": "TIER_3",
        "region": "Likely native Southeast Asia; invasive across ~90% of tropical Pacific island territories, present in India.",
        "zone": "SA",
        "isNonFlying": True,
        "tempRange": [0, 50],
        "tempText": "Population dynamics linked to winter temperature.",
        "humidityRange": [0, 100],
        "humidityText": "N/A for flight specifically.",
        "rainfallPattern": "Monthly precipitation accumulation affects population dynamics (not a flight trigger).",
        "condition": "none",
        "windMax": 99,
        "windText": "N/A",
        "timingText": "N/A",
        "months": [],
        "timeOfDay": [],
        "notes": "Forms large supercolonies with intranidal mating; true dispersal nuptial flights are rare or absent in most populations.",
        "source": "Thomas, Becker, Abbott & Feldhaar (2010); Lin, Yeh, Wu & Wu (2023) Biology 12(12):1482."
    },
    {
        "id": "WAS-AUR",
        "name": "Little Fire Ant / Electric Ant",
        "sci": "Wasmannia auropunctata",
        "tier": "TIER_3",
        "region": "Native Central/South America; invasive worldwide in the tropics.",
        "zone": "GLOBAL",
        "isNonFlying": True,
        "tempRange": [0, 50],
        "tempText": "N/A",
        "humidityRange": [0, 100],
        "humidityText": "N/A",
        "rainfallPattern": "N/A",
        "condition": "none",
        "windMax": 99,
        "windText": "N/A",
        "timingText": "N/A",
        "months": [],
        "timeOfDay": [],
        "notes": "Documented alongside L. humile, M. pharaonis and A. gracilipes as sharing the tramp-ant reproductive syndrome.",
        "source": "Fournier et al. (2005), as reviewed in Eyer, Blumenfeld & Vargo (2019)."
    },

    # --- TIER 4 (Citizen-Science) ---
    {
        "id": "CAR-DIV",
        "name": "Asian Marauder Ant",
        "sci": "Carebara diversa",
        "tier": "TIER_4",
        "region": "India and broader Southeast Asia.",
        "zone": "SA",
        "tempRange": [24, 34],
        "tempText": "Warm days.",
        "humidityRange": [65, 95],
        "humidityText": "High humidity required.",
        "rainfallPattern": "Most frequently sighted actively flying immediately after rainfall when soil is moist.",
        "condition": "after_rain",
        "windMax": 12,
        "windText": "Not quantified.",
        "timingText": "Primarily monsoon season; daylight/afternoon windows commonly reported by antkeepers.",
        "months": [5, 6, 7, 8, 9],
        "timeOfDay": ["afternoon", "dusk", "evening"],
        "notes": "Extremely popular in the pet trade; highly dependent on post-rain humidity for the survival of the large queens before founding.",
        "source": "Aggregated hobbyist care literature and regional sighting reports (e.g., BestAntsUK community data)."
    },
    {
        "id": "TET-RUF",
        "name": "Arboreal Bicolored Ant",
        "sci": "Tetraponera rufonigra",
        "tier": "TIER_4",
        "region": "India, Southeast Asia (including Malaysia).",
        "zone": "SA",
        "tempRange": [24, 35],
        "tempText": "Warm, daytime temperatures.",
        "humidityRange": [35, 80],
        "humidityText": "Capable of flying outside of peak humidity/rain events.",
        "rainfallPattern": "Not strictly rain-dependent; uniquely reported to fly on dry days unlike many ground-nesting species.",
        "condition": "warm_calm_afternoon",
        "windMax": 15,
        "windText": "Not quantified.",
        "timingText": "Daytime flights commonly reported.",
        "months": [4, 5, 6, 7, 8, 9, 10],
        "timeOfDay": ["morning", "afternoon"],
        "notes": "A frequently encountered arboreal pseudomyrmecine; citizen data notes it often flies during the day without the strict rain triggers required by ground-nesting local species.",
        "source": "AntFlights.com registry data; regional ant-keeping community observations (e.g., AntsDIY)."
    },
    {
        "id": "CAM-LIG",
        "name": "Giant European Carpenter Ant",
        "sci": "Camponotus ligniperda",
        "tier": "TIER_4",
        "region": "Central / Western Europe.",
        "zone": "EU",
        "tempRange": [18, 28],
        "tempText": "Not quantified; earlier flights recorded following unusually warm spring.",
        "humidityRange": [40, 85],
        "humidityText": "Not quantified.",
        "rainfallPattern": "Not specifically isolated.",
        "condition": "warm_calm_afternoon",
        "windMax": 14,
        "windText": "Not quantified.",
        "timingText": "Normally late May–June; citizen data recorded flights as early as 21 May after a warm spring.",
        "months": [5, 6],
        "timeOfDay": ["afternoon", "evening"],
        "notes": "Included to show how much year-to-year variance exists even within a documented 'normal' window.",
        "source": "AntonTop 2026 European Nuptial Flight Calendar."
    },
    {
        "id": "FOR-RUF",
        "name": "Red Wood Ant",
        "sci": "Formica rufa",
        "tier": "TIER_4",
        "region": "Europe.",
        "zone": "EU",
        "tempRange": [16, 26],
        "tempText": "Not quantified.",
        "humidityRange": [45, 85],
        "humidityText": "Not quantified.",
        "rainfallPattern": "Not quantified.",
        "condition": "warm_calm_afternoon",
        "windMax": 14,
        "windText": "Not quantified.",
        "timingText": "Late May–June, overlapping with C. ligniperda.",
        "months": [5, 6],
        "timeOfDay": ["afternoon"],
        "notes": "Multiple species frequently fly on the same evenings once regional weather triggers align, per aggregated observations.",
        "source": "AntonTop 2026 European Nuptial Flight Calendar."
    },
    {
        "id": "MES-STR",
        "name": "European Harvester Ant",
        "sci": "Messor structor / Tetramorium spp.",
        "tier": "TIER_4",
        "region": "Central and Eastern Europe.",
        "zone": "EU",
        "tempRange": [22, 32],
        "tempText": "Not quantified.",
        "humidityRange": [40, 80],
        "humidityText": "Not quantified.",
        "rainfallPattern": "Not quantified.",
        "condition": "hot_dry_afternoon",
        "windMax": 12,
        "windText": "Not quantified.",
        "timingText": "June–July (M. structor slightly later than M. barbarus further south).",
        "months": [6, 7],
        "timeOfDay": ["afternoon"],
        "notes": "Congeneric comparison with the Tier-1 M. barbarus entry shows a clear latitudinal shift in flight timing.",
        "source": "AntonTop 2026 European Nuptial Flight Calendar."
    },

    # --- TIER 5 (India-Specific Context: Monsoon Biology) ---
    {
        "id": "HAR-SAL",
        "name": "Indian Jumping Ant (Jerdon's)",
        "sci": "Harpegnathos saltator",
        "tier": "TIER_5",
        "region": "India (type locality) and Sri Lanka; well studied in Karnataka, Kerala, Tamil Nadu.",
        "zone": "SA",
        "tempRange": [22, 32],
        "tempText": "Not documented for flight specifically.",
        "humidityRange": [60, 95],
        "humidityText": "Not documented for flight specifically.",
        "rainfallPattern": "Not documented as a flight trigger. What IS documented: nest architecture to withstand monsoon rains.",
        "condition": "after_rain",
        "windMax": 12,
        "windText": "Not quantified.",
        "timingText": "Not documented for flight timing specifically.",
        "months": [6, 7, 8, 9],
        "timeOfDay": ["evening"],
        "notes": "One of the most-studied Indian ant species overall, yet its nuptial flight triggers remain largely unquantified in peer-reviewed literature.",
        "source": "Peeters, Bourgoin & Hölldobler (1994); AntWiki."
    },
    {
        "id": "DIA-IND",
        "name": "Indian Diacamma Ant",
        "sci": "Diacamma indicum",
        "tier": "TIER_5",
        "region": "India (studied in West Bengal / Kolkata region).",
        "zone": "SA",
        "tempRange": [24, 32],
        "tempText": "Not documented for flight specifically.",
        "humidityRange": [65, 95],
        "humidityText": "Not documented for flight specifically.",
        "rainfallPattern": "Not documented as a flight trigger. What IS documented: a 'dual response' to monsoon nest flooding.",
        "condition": "calm_mild_morning",
        "windMax": 12,
        "windText": "Not quantified.",
        "timingText": "Queenless ponerine (gamergates); males fly but timing unquantified.",
        "months": [6, 7, 8],
        "timeOfDay": ["morning"],
        "notes": "Directly relevant to monsoon biology and nest-site selection in the Indian context, but the published study focuses on survival, not flight.",
        "source": "Kolay & Annagiri (2015) Scientific Reports 5:13716."
    },

    # --- TIER 6 (Additional India-Occurring Species - Predicted) ---
    {
        "id": "CAM-COM",
        "name": "Golden-tailed Black Ant",
        "sci": "Camponotus compressus",
        "tier": "TIER_6",
        "predictionBasis": "Congeneric with Camponotus ligniperda (Tier 4)",
        "confidence": "LOW",
        "region": "Indian cities and rural habitats nationwide.",
        "zone": "SA",
        "tempRange": [25, 35],
        "tempText": "Predicted ~25–35°C based on urban active periods.",
        "humidityRange": [55, 95],
        "humidityText": "Predicted elevated post-monsoon humidity.",
        "rainfallPattern": "Predicted to follow monsoon rainfall pulses.",
        "condition": "after_rain",
        "windMax": 14,
        "windText": "Predicted low to moderate wind.",
        "timingText": "Commonly observed at dusk/evening during monsoon months (June–August).",
        "months": [6, 7, 8],
        "timeOfDay": ["dusk", "evening"],
        "notes": "Faunally confirmed across India; flight timing inferred from congenerics and regional surveys.",
        "source": "Faunal checklists (Bharti et al. 2016); inferred from Tier 4 C. ligniperda."
    },
    {
        "id": "SOL-GEM",
        "name": "Tropical Fire Ant",
        "sci": "Solenopsis geminata",
        "tier": "TIER_6",
        "predictionBasis": "Congeneric with Solenopsis invicta (Tier 1)",
        "confidence": "MODERATE",
        "region": "Widespread across peninsular India and urban areas.",
        "zone": "SA",
        "tempRange": [25, 35],
        "tempText": "Predicted 25–35°C based on S. invicta Tier 1 data.",
        "humidityRange": [60, 85],
        "humidityText": "Predicted 60–80% RH.",
        "rainfallPattern": "Predicted within 24–48 hours after rain events.",
        "condition": "after_rain",
        "windMax": 10,
        "windText": "Calm, <10 km/h.",
        "timingText": "Afternoon to dusk during monsoon season (May–September).",
        "months": [5, 6, 7, 8, 9],
        "timeOfDay": ["afternoon", "evening"],
        "notes": "Invasive/pantropical tramp congener of S. invicta with similar physiological thresholds.",
        "source": "Inferred from Tier 1 S. invicta data (Xu et al. 2009; LSU AgCenter)."
    },
    {
        "id": "DIA-RUG",
        "name": "Rugose Ponerine Ant",
        "sci": "Diacamma rugosum",
        "tier": "TIER_6",
        "predictionBasis": "Congeneric with Diacamma indicum (Tier 5)",
        "confidence": "LOW-MODERATE",
        "region": "Indian urban surveys and forest leaf litter.",
        "zone": "SA",
        "tempRange": [24, 32],
        "tempText": "Predicted warm monsoon temperatures.",
        "humidityRange": [60, 95],
        "humidityText": "High humidity.",
        "rainfallPattern": "Post-monsoon ground moisture.",
        "condition": "calm_mild_morning",
        "windMax": 12,
        "windText": "Calm.",
        "timingText": "Morning / dusk flights by males.",
        "months": [6, 7, 8],
        "timeOfDay": ["morning", "dusk"],
        "notes": "Queenless ponerine reproductive biology inferred from D. indicum.",
        "source": "Inferred from Diacamma indicum (Tier 5)."
    },
    {
        "id": "ODO-TRA",
        "name": "Asian Ponerine Ant",
        "sci": "Odontoponera transversa / Odontomachus simillimus",
        "tier": "TIER_6",
        "predictionBasis": "Subfamily analog: Harpegnathos saltator (Tier 5)",
        "confidence": "LOW",
        "region": "South and Southeast Asia.",
        "zone": "SA",
        "tempRange": [24, 32],
        "tempText": "Warm tropical.",
        "humidityRange": [65, 95],
        "humidityText": "Humid post-rain evenings.",
        "rainfallPattern": "Monsoon rainy season.",
        "condition": "after_rain",
        "windMax": 12,
        "windText": "Calm.",
        "timingText": "Evening / dusk.",
        "months": [6, 7, 8],
        "timeOfDay": ["evening"],
        "notes": "Subfamily Ponerinae analog; ground nest exit following monsoon showers.",
        "source": "Faunal checklists; inferred from Tier 5 ponerine biology."
    },
    {
        "id": "PAR-LON",
        "name": "Longhorn Crazy Ant",
        "sci": "Paratrechina longicornis",
        "tier": "TIER_6",
        "predictionBasis": "Partial analog: tramp-ant syndrome (Tier 3, partial)",
        "confidence": "LOW",
        "region": "Cosmopolitan tramp ant in Indian cities.",
        "zone": "SA_GLOBAL",
        "tempRange": [24, 34],
        "tempText": "Warm temperatures.",
        "humidityRange": [40, 90],
        "humidityText": "Wide tolerance.",
        "rainfallPattern": "Not strictly rain-bound; partial budding dispersal.",
        "condition": "warm_calm_afternoon",
        "windMax": 14,
        "windText": "Low wind.",
        "timingText": "Warm season afternoons/evenings.",
        "months": [5, 6, 7, 8, 9],
        "timeOfDay": ["afternoon", "evening"],
        "notes": "Tramp species with mixed dispersal — some male flight, queen dispersal mostly budding.",
        "source": "Tramp-ant reproductive syndrome literature."
    },
    {
        "id": "TAP-MEL",
        "name": "Ghost Ant",
        "sci": "Tapinoma melanocephalum",
        "tier": "TIER_6",
        "predictionBasis": "Tramp-ant reproductive syndrome (Tier 3)",
        "confidence": "MODERATE (Exception)",
        "region": "Ubiquitous indoor/urban tramp ant in India.",
        "zone": "SA_GLOBAL",
        "isNonFlying": True,
        "tempRange": [0, 50],
        "tempText": "N/A",
        "humidityRange": [0, 100],
        "humidityText": "N/A",
        "rainfallPattern": "N/A",
        "condition": "none",
        "windMax": 99,
        "windText": "N/A",
        "timingText": "N/A (Budding)",
        "months": [],
        "timeOfDay": [],
        "notes": "Tramp species: highly polygynous supercolonies that reproduce via budding rather than aerial nuptial flights.",
        "source": "Inferred from tramp ant syndrome (Tier 3)."
    },
    {
        "id": "CRE-SUB",
        "name": "Indian Acrobat Ant",
        "sci": "Crematogaster subnuda / C. ransonneti",
        "tier": "TIER_6",
        "predictionBasis": "Ecological analog: Oecophylla smaragdina (Tier 2)",
        "confidence": "LOW",
        "region": "Arboreal and carton-nesting across India.",
        "zone": "SA",
        "tempRange": [25, 34],
        "tempText": "Warm canopy temperatures.",
        "humidityRange": [55, 95],
        "humidityText": "Monsoon humidity.",
        "rainfallPattern": "Monsoon rainy period.",
        "condition": "after_rain",
        "windMax": 12,
        "windText": "Low wind.",
        "timingText": "Late afternoon to dusk.",
        "months": [6, 7, 8, 9],
        "timeOfDay": ["afternoon", "dusk"],
        "notes": "Arboreal ecological analog of Oecophylla; flights correlate with monsoon wet spells.",
        "source": "Inferred from Tier 2 arboreal Weaver ant pattern."
    },
    {
        "id": "PHE-SPP",
        "name": "Indian Big-headed Ants",
        "sci": "Pheidole spp.",
        "tier": "TIER_6",
        "predictionBasis": "Genus study: Pheidole sitarches (direct genus citation)",
        "confidence": "MODERATE (genus)",
        "region": "Common soil and pavement nesting ants in India.",
        "zone": "SA",
        "tempRange": [24, 33],
        "tempText": "24–33°C.",
        "humidityRange": [60, 90],
        "humidityText": "Elevated post-rain humidity.",
        "rainfallPattern": "After warm summer/monsoon rain events.",
        "condition": "after_rain",
        "windMax": 10,
        "windText": "Calm.",
        "timingText": "Evening / night.",
        "months": [5, 6, 7, 8],
        "timeOfDay": ["evening"],
        "notes": "Pheidole genus is well-documented for synchronized post-rain evening nuptial flights.",
        "source": "Pheidole sitarches genus-level citations in Gómez & Abril (2012)."
    },
    {
        "id": "POL-LAC",
        "name": "Spiny Ant",
        "sci": "Polyrhachis lacteipennis and other spp.",
        "tier": "TIER_6",
        "predictionBasis": "Ecological analog: O. smaragdina / C. compressus",
        "confidence": "LOW",
        "region": "Open scrub, trees and urban foliage across India.",
        "zone": "SA",
        "tempRange": [25, 35],
        "tempText": "Warm daytime/evening.",
        "humidityRange": [50, 90],
        "humidityText": "Monsoon humidity.",
        "rainfallPattern": "Post-monsoon showers.",
        "condition": "after_rain",
        "windMax": 12,
        "windText": "Calm.",
        "timingText": "Dusk / evening.",
        "months": [6, 7, 8],
        "timeOfDay": ["dusk", "evening"],
        "notes": "Arboreal/epigeic spiny ants; inferred from co-occurring Camponotini relatives.",
        "source": "Urban checklists; inferred from Camponotus / Oecophylla analogs."
    },
    # --- INVASIVE SPECIES IN INDIA WITH NUPTIAL FLIGHTS ---
    {
        "id": "TRI-DES",
        "name": "Singapore Ant (Destructive Trailing Ant)",
        "sci": "Trichomyrmex destructor",
        "tier": "TIER_6",
        "isInvasive": True,
        "predictionBasis": "Invasive urban tramp ant with documented nocturnal swarms",
        "confidence": "MODERATE",
        "region": "Invasive across India (Bangalore, Chennai, Mumbai, Delhi, urban centers).",
        "zone": "SA_GLOBAL",
        "tempRange": [25, 36],
        "tempText": "25–36°C warm evenings / nights.",
        "humidityRange": [60, 95],
        "humidityText": "Elevated humidity (>60% RH).",
        "rainfallPattern": "Pre-monsoon and monsoon humidity pulses; alates fly to outdoor and porch lights.",
        "condition": "humid_still_evening",
        "windMax": 10,
        "windText": "Calm nocturnal air, <10 km/h.",
        "timingText": "May to September; nocturnal and crepuscular flights (19:00–23:00).",
        "months": [5, 6, 7, 8, 9],
        "timeOfDay": ["dusk", "evening"],
        "notes": "Invasive urban pest in India. Unlike Pharaoh ants, T. destructor alate queens and males perform nighttime aerial flights towards artificial lights before mating.",
        "source": "Wetterer (2009) Myrmecological News 12:157–177; Indian urban pest surveys."
    },
    {
        "id": "TET-BIC",
        "name": "Bicolored Penny Ant (Guinea Ant)",
        "sci": "Tetramorium bicarinatum",
        "tier": "TIER_6",
        "isInvasive": True,
        "predictionBasis": "Invasive tramp ant with short dispersal flights",
        "confidence": "MODERATE",
        "region": "Invasive pantropical tramp ant established in urban gardens, greenhouses, and coastal disturbed areas across India.",
        "zone": "SA_GLOBAL",
        "tempRange": [24, 34],
        "tempText": "24–34°C.",
        "humidityRange": [65, 95],
        "humidityText": "High humidity (>65% RH).",
        "rainfallPattern": "Flights cluster in warm periods after monsoon rains.",
        "condition": "after_rain",
        "windMax": 12,
        "windText": "Low wind, <12 km/h.",
        "timingText": "June to October; late afternoon to dusk windows.",
        "months": [6, 7, 8, 9, 10],
        "timeOfDay": ["afternoon", "dusk", "evening"],
        "notes": "Invasive tramp ant; alate queens engage in localized dispersal flights and swarm near nest entrances under warm humid conditions.",
        "source": "Wetterer (2009) Sociobiology 54:797–810; Bharti, Guénard, Bharti & Economo (2016)."
    },
    {
        "id": "NYL-BOU",
        "name": "Bourbon Crazy Ant (Rover Ant)",
        "sci": "Nylanderia bourbonica",
        "tier": "TIER_6",
        "isInvasive": True,
        "predictionBasis": "Invasive tramp ant with prolific light-attracted swarms",
        "confidence": "MODERATE",
        "region": "Invasive pantropical tramp ant established in Indian urban landscapes and coastal zones.",
        "zone": "SA_GLOBAL",
        "tempRange": [24, 34],
        "tempText": "24–34°C.",
        "humidityRange": [55, 90],
        "humidityText": "Warm, muggy evenings.",
        "rainfallPattern": "Summer and monsoon post-rain periods.",
        "condition": "humid_still_evening",
        "windMax": 12,
        "windText": "Calm airflow, <12 km/h.",
        "timingText": "May to September; crepuscular and evening swarms around streetlights.",
        "months": [5, 6, 7, 8, 9],
        "timeOfDay": ["dusk", "evening"],
        "notes": "Invasive urban ant; prolific alate producer. Males and queens frequently swarm near lights on muggy evenings.",
        "source": "Kallal & Lapolla (2012) Zootaxa; Bharti et al. (2016)."
    },
    {
        "id": "PHE-MEG",
        "name": "African Big-Headed Ant",
        "sci": "Pheidole megacephala",
        "tier": "TIER_6",
        "isInvasive": True,
        "predictionBasis": "Invasive tramp ant with post-rain flight swarms",
        "confidence": "MODERATE",
        "region": "Invasive tramp ant documented in southern and western India (e.g. Maharashtra, Karnataka).",
        "zone": "SA_GLOBAL",
        "tempRange": [22, 32],
        "tempText": "22–32°C.",
        "humidityRange": [70, 95],
        "humidityText": "High humidity following rain.",
        "rainfallPattern": "Strongly triggered 1–2 days after monsoon rain events.",
        "condition": "after_rain",
        "windMax": 10,
        "windText": "Calm, <10 km/h.",
        "timingText": "May to August; early mornings or dusk.",
        "months": [5, 6, 7, 8],
        "timeOfDay": ["morning", "dusk"],
        "notes": "One of the world's worst 100 invasive species. Winged alates perform localized nuptial flights when humidity is elevated after rainfall.",
        "source": "Hoffmann (1998); Global Invasive Species Database (GISD); Bharti et al. (2016)."
    }
]

RAG_CHUNKS = [
    {
        "id": "CHUNK-META-01",
        "title": "Dataset Purpose & Anti-Hallucination Methodology",
        "tier": "METADATA",
        "content": "Why this dataset looks the way it does: Ant nuptial-flight triggers are one of the most under-documented areas of myrmecology. Even for well-studied invasive pests, most 'data' in circulation online is anecdotal rather than peer-reviewed field measurement. Rather than inventing precise numbers for species with no real record — which would poison a RAG index with confident-sounding fabrications — this document only includes species for which some form of documented evidence exists, graded into confidence tiers (Tiers 1 to 6). Every entry carries its source.",
        "keywords": ["purpose", "methodology", "hallucination", "tiers", "confidence", "anecdotal", "myrmecology", "dataset"],
        "source": "Ant Nuptial Flight Trigger Factors PDF, Page 1"
    },
    {
        "id": "CHUNK-META-02",
        "title": "Confidence Tier Definitions (Tiers 1–6)",
        "tier": "METADATA",
        "content": "TIER 1 — Quantified experimental/field data: peer-reviewed studies that measured actual temperature, humidity, wind, or timing thresholds against observed flights.\nTIER 2 — Documented qualitative pattern: peer-reviewed or authoritative sources describing seasonal timing and general trigger conditions without precise numeric thresholds.\nTIER 3 — Reproductive-strategy exceptions: species documented to NOT perform classic aerial nuptial flights at all (supercolonial/tramp species) — an important negative data point for a RAG system, so it doesn't force-fit 'flight factors' onto species that disperse by budding instead.\nTIER 4 — Citizen-science / antkeeping community data: aggregated hobbyist observation calendars. Directionally useful but treat as lower confidence.\nTIER 5 — India-Specific Context: literature documents monsoon-adaptive biology in detail, but does NOT report specific nuptial-flight weather triggers.\nTIER 6 — Additional India-Occurring Species (Predicted): inferred from closest relatives in Tiers 1–5; explicitly NOT verified species-specific data.",
        "keywords": ["tier 1", "tier 2", "tier 3", "tier 4", "tier 5", "tier 6", "definitions", "confidence", "monsoon", "exceptions"],
        "source": "Ant Nuptial Flight Trigger Factors PDF, Pages 1, 9, 10"
    },
    {
        "id": "CHUNK-EDITOR-NOTE",
        "title": "Editor's Note: Revision History & Citation Audit (Camponotus sericeus Caveat)",
        "tier": "METADATA",
        "content": "This update adds Carebara diversa and Tetraponera rufonigra (Tier 4, citizen-science) and Camponotus sericeus (Tier 2, documented qualitative pattern). One issue was flagged rather than silently corrected: the Camponotus sericeus entry cites 'Kipyatkov, V.E. (2018)' for a specific claim that Indian flights occur strictly in September–October. The actual 2018 IntechOpen chapter is authored by E.B. Lopatina, not Kipyatkov, and is a general review of seasonal-cycle biology in Russian/Palearctic ants — it does not appear to contain India-specific Camponotus sericeus flight-timing data. The underlying claim could not be independently verified against that source and should be treated as lower-confidence than the rest of Tier 2 until a better citation is located.",
        "keywords": ["editor", "revision", "camponotus sericeus", "kipyatkov", "lopatina", "carebara diversa", "tetraponera rufonigra", "caveat", "citation"],
        "source": "Ant Nuptial Flight Trigger Factors PDF, Page 11"
    },
    {
        "id": "CHUNK-INDIA-SUMMARY",
        "title": "India Myrmecology Overview & 828+ Species Context",
        "tier": "METADATA",
        "content": "India hosts 828+ recognized ant species/subspecies across 100 genera nationally (Bharti, Guénard, Bharti & Economo 2016); the overwhelming majority have no published nuptial-flight data of any kind, documented or predicted. Field predictions for most Indian species must rely on congeneric ecological analogs or citizen science records until further field measurements are published.",
        "keywords": ["india", "828 species", "bharti", "genera", "faunal checklist", "under-documented"],
        "source": "Ant Nuptial Flight Trigger Factors PDF, Page 10"
    }
]

INDIA_SPECIES_IDS = {
    'OEC-SMA', 'CAM-SER', 'MON-PHA', 'ANO-GRA', 'CAR-DIV', 
    'TET-RUF', 'HAR-SAL', 'DIA-IND', 'CAM-COM', 'SOL-GEM', 
    'DIA-RUG', 'ODO-TRA', 'PAR-LON', 'TAP-MEL', 'CRE-SUB', 
    'PHE-SPP', 'POL-LAC', 'TRI-DES', 'TET-BIC', 'NYL-BOU', 'PHE-MEG'
}

# Generate chunk per species for fine-grained retrieval
for sp in SPECIES_DATA:
    sp['isFoundInIndia'] = sp['id'] in INDIA_SPECIES_IDS
    non_fly_note = " [CRITICAL EXCEPTION: This species does not fly; it mates intranidally / disperses by budding]" if sp.get("isNonFlying") else ""
    pred_note = f" [Prediction basis: {sp.get('predictionBasis')} | Confidence: {sp.get('confidence')}]" if sp.get("predictionBasis") else ""
    content = f"Species: {sp['name']} ({sp['sci']}){non_fly_note}\n" \
              f"Tier: {sp['tier']} ({TIER_DEFINITIONS[sp['tier']]['title']})\n" \
              f"Found in India: {'Yes (Native or Established)' if sp['isFoundInIndia'] else 'No (Exotic / Non-Indian Range)'}\n" \
              f"Region/Origin: {sp['region']}\n" \
              f"Temperature: {sp['tempText']}\n" \
              f"Humidity: {sp['humidityText']}\n" \
              f"Rainfall Pattern: {sp['rainfallPattern']}\n" \
              f"Wind: {sp['windText']}\n" \
              f"Timing (Season / Time-of-day): {sp['timingText']}\n" \
              f"Notes: {sp['notes']}{pred_note}\n" \
              f"Source: {sp['source']}"
    
    keywords = [
        sp['name'].lower(),
        sp['sci'].lower(),
        sp['tier'].lower(),
        sp['condition'].lower(),
        sp.get('zone', '').lower(),
        "species dossier"
    ]
    if sp['isFoundInIndia']:
        keywords.extend(["india", "indian species", "south asia"])
    if sp.get("isNonFlying"):
        keywords.extend(["non-flying", "tramp", "budding", "intranidal", "exception"])

    RAG_CHUNKS.append({
        "id": f"CHUNK-SP-{sp['id']}",
        "title": f"Dossier: {sp['name']} ({sp['sci']}) — {TIER_DEFINITIONS[sp['tier']]['badge']}",
        "tier": sp['tier'],
        "speciesId": sp['id'],
        "content": content,
        "keywords": keywords,
        "source": sp['source']
    })

def main():
    workspace = os.path.dirname(os.path.abspath(__file__))
    
    # 1. Output nuptial_rag_dataset.json
    json_path = os.path.join(workspace, "nuptial_rag_dataset.json")
    dataset = {
        "metadata": {
            "title": "Ant Nuptial Flight Trigger Factors — Source-Referenced RAG Dataset",
            "version": "2.1-updated",
            "total_species": len(SPECIES_DATA),
            "total_chunks": len(RAG_CHUNKS),
            "tiers": TIER_DEFINITIONS
        },
        "species": SPECIES_DATA,
        "chunks": RAG_CHUNKS
    }
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(dataset, f, indent=2, ensure_ascii=False)
    print(f"Wrote {json_path} with {len(SPECIES_DATA)} species and {len(RAG_CHUNKS)} RAG chunks.")

    # 2. Output rag_data.js (Browser module)
    js_path = os.path.join(workspace, "rag_data.js")
    js_content = "/* Ant Nuptial Flight Trigger Factors — Grounded RAG Knowledge Base */\n" \
                 "window.ANT_RAG_DATA = " + json.dumps(dataset, indent=2, ensure_ascii=False) + ";\n"
    with open(js_path, "w", encoding="utf-8") as f:
        f.write(js_content)
    print(f"Wrote {js_path} for browser consumption.")

if __name__ == "__main__":
    main()
